grouptask/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import contactView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup' ),
    path('contact/', contactView, name='contact'),
]

grouptask/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),

    path('accounts/', include('grouptask.accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.LoginConfView.as_view(), name='login_conf'),
    path('logout/', views.LogoutConfView.as_view(), name='logout_conf'),

    path('projects/', views.ProjectListView.as_view(), name='projects'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('projects/create/', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/<int:pk>/update/', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),

    path('tasks/list/', views.TasksListView.as_view(), name='list_tasks'),
    path('tasks/add/', views.create_task, name='create_task'),
    path('tasks/task_update/<str:pk>/', views.update_task, name='update'),
    path('tasks/task_remove/<str:pk>/', views.remove_task, name='remove'),
    path('tasks/todo/', views.TaskTodoListView.as_view(), name='list_task_todos'),
    path('tasks/todo_update/<str:pk>/', views.update_todo, name='update_todo'),
    path('tasks/todo/add/', views.create_task_todo, name='create_task_todo'),
    path('tasks/todo/remove/<str:pk>/', views.remove_todo_task, name='remove_todo'),

    path('admin/', admin.site.urls),
]

templates/pages/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <title>Home page</title>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<link rel="stylesheet" href="{% static 'css/master.css' %}" type="text/css" />

<body>
<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>GroupTask</b></h3>
  </div>
  <div class="w3-bar-block">
      {% if user.is_authenticated %}
        <p>Hello, {{ user.username }}.</p>
        <a href="{% url 'projects' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Projects</a>
        <ul><a href="{% url 'list_tasks' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Tasks</a></ul>
        <ul><a href="{% url 'list_task_todos' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">ToDo</a></ul>
        <a href="{% url 'accounts:logout' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Logout</a>
      {% else %}
        <a href="{% url 'home' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Home</a>
        <a href="{% url 'accounts:login' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Log In</a>
        <a href="{% url 'accounts:signup' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Sing Up</a>
        <a href="{% url 'accounts:contact' %}" onclick="w3_close()" class="w3-bar-item w3-button w3-hover-white">Contact</a>
      {% endif %}
  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>GroupTask</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

{% block content %}
{% endblock %}

<!-- Footer Container -->
  <footer id="footer">
       <div class="w3-light-grey w3-container w3-padding-32" style="margin-top:75px;padding-right:58px">
           <p class="w3-right">All rights reserved  &copy; {% now 'Y' %}, Powered by Regina Dvaržeckytė & Vaida Bernotienė</p>
       </div>
  </footer>

<!-- Script Container -->
<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}

</script>

</body>
</html>

templates/pages/email.html
{% extends "pages/base.html" %}
{% load static %}
{% load bootstrap3 %}
{% block content %}

<div class="jumbotron"><br></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

    <!-- Header -->
    <!-- Contact -->
    <div class="w3-container" style="margin-top:80px" id="showcase">
      <h1 class="w3-xxxlarge w3-text-red"><b>Contact Us</b></h1>
      <hr style="width:300px;border:5px solid red" class="w3-round">
      <p>Do you want to make your job easier? Fill out the form and fill us in with the details.</p>
      <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="w3-button w3-block w3-padding-large w3-red w3-margin-bottom">Send</button>
      </form>
    </div>
</div>

<!-- End page content -->

{% endblock %}

templates/pages/index.html
{% extends "pages/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron">
    <h1>GroupTask</h1>
</div>
<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
      <h1 class="w3-jumbo"><b>Projects and Tasks manager!</b></h1>
      <h1 class="w3-xxxlarge w3-text-red"><b>Let's go!</b></h1>
      <hr style="width:210px;border:5px solid red" class="w3-round">
  </div>

  <!-- Photo grid (modal) -->
  <div class="w3-row-padding">
    <div class="w3-half">
      <img src="{% static 'images/lot-stickers.jpg' %}" style="width:100%" onclick="onClick(this)" alt="Create Project">
    </div>

    <div class="w3-half">
      <img src="{% static 'images/lot-stickers.jpg' %}" style="width:100%" onclick="onClick(this)" alt="Create Task for existing Project">
    </div>
  </div>

  <!-- Modal for full size images on click-->
  <div id="modal01" class="w3-modal w3-black" style="padding-top:0" onclick="this.style.display='none'">
    <span class="w3-button w3-black w3-xxlarge w3-display-topright">×</span>
    <div class="w3-modal-content w3-animate-zoom w3-center w3-transparent w3-padding-64">
      <img id="img01" class="w3-image">
      <p id="caption"></p>
    </div>
  </div>

</div>
{% endblock %}

templates/pages/our_team.html
{% extends "pages/base.html" %}
{% load static %}
{% block content %}

<div class="jumbotron"><br></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">
<!-- Our team -->
  <div class="w3-container" id="ourteam" style="margin-top:75px">
    <h1 class="w3-xxxlarge w3-text-red"><b>Our Team</b></h1>
    <hr style="width:250px;border:5px solid red" class="w3-round">
    <p></p>
    <p></p>
  </div>

  <!-- The Team -->
  <div class="w3-row-padding w3-grayscale">
    <div class="w3-col m4 w3-margin-bottom">
      <div class="w3-light-grey">
        <img src="{% static 'images/ReginaDv.jpg' %}" alt="Regina" style="width:100%">
        <div class="w3-container">
          <h3>Regina Dvaržeckytė</h3>
          <p class="w3-opacity">Project manager & Developer</p>
        </div>
      </div>
    </div>
    <div class="w3-col m4 w3-margin-bottom">
      <div class="w3-light-grey">
        <img src="{% static 'images/VaidaBr.jpg' %}" alt="Vaida" style="width:100%">
        <div class="w3-container">
          <h3>Vaida Bernotienė</h3>
          <p class="w3-opacity">Designer & Developer</p>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- End page content -->

{% endblock %}